# Generated by Django 3.2.14 on 2022-07-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='USER', on_delete=django.db.models.deletion.CASCADE, to='users.userprofilerole', verbose_name='Rol de usuario'),
        ),
    ]
