# Generated by Django 3.2.14 on 2022-08-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active'),
        ),
    ]
