# Generated by Django 3.2.14 on 2022-08-01 08:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import training_fyg.courses.models.courses
import training_fyg.courses.models.lessons


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del curso')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción del curso')),
                ('course_type', models.CharField(choices=[('public', 'public'), ('private', 'private')], help_text='Tipo de curso, accesible publicamente o por invitación', max_length=12, verbose_name='Tipo de curso')),
                ('categories', models.ManyToManyField(blank=True, related_name='courses', to='categories.CategoryCourse')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_course_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema del curso')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción del tema a tratar')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_coursemodule_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_coursemodule_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Módulo del curso',
                'verbose_name_plural': 'Módulos del curso',
            },
        ),
        migrations.CreateModel(
            name='HomeworkLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('title', models.CharField(default='Título de la tarea', max_length=120, verbose_name='título')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción de la tarea')),
                ('status_type', models.CharField(choices=[('Revisado', 'Revisado'), ('Pendiente', 'Pendiente')], default='Pendiente', help_text='Estatus revision', max_length=10, verbose_name='Estatus revision')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklesson_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
            ],
            options={
                'verbose_name': 'Tarea de la leccion',
                'verbose_name_plural': 'Tareas de las lecciones',
            },
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maestros', to='courses.course', verbose_name='curso')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_teachercourse_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_teachercourse_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('user', models.ForeignKey(blank=True, help_text='registro de profesor en un curso', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profesor en un curso')),
            ],
            options={
                'verbose_name': 'Registro de maestro en curso',
                'verbose_name_plural': 'Registros de maestros en cursos',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course', verbose_name='curso')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_studentcourse_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_studentcourse_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('user', models.ForeignKey(blank=True, help_text='registro de estudiante en un curso', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='estudiante en un curso')),
            ],
            options={
                'verbose_name': 'Registro de estudiante en curso',
                'verbose_name_plural': 'Registros de estudiantes en cursos',
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('resource', models.FileField(max_length=500, upload_to=training_fyg.courses.models.lessons.lesson_resource_directory_path, verbose_name='Recurso')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_lessonresource_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_lessonresource_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Recurso de la lección',
                'verbose_name_plural': 'Recursos de la lección',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema del curso')),
                ('description', models.TextField(max_length=10000, verbose_name='Descripción del tema a tratar')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_lesson_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_lesson_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule', verbose_name='clase')),
                ('resource', models.ManyToManyField(blank=True, related_name='lesson_resources', to='courses.LessonResource', verbose_name='Recursos de la lección')),
            ],
            options={
                'verbose_name': 'Lección del módulo',
                'verbose_name_plural': 'Lecciones del módulo',
            },
        ),
        migrations.CreateModel(
            name='ImagesLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('resource', models.FileField(help_text='son los recursos que se mostraran', upload_to='', verbose_name='recurso embebido')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_imageslesson_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_imageslesson_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Recurso de la clase',
                'verbose_name_plural': 'Recurso de la clase',
            },
        ),
        migrations.CreateModel(
            name='HomeworkLessonReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('qualification', models.FloatField(blank=True, null=True, verbose_name='Calificacion')),
                ('review', models.TextField(max_length=10000, verbose_name='Revision de la tarea')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklessonreview_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('homework_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworklessonreview', to='courses.homeworklesson', verbose_name='tarea leccion')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklessonreview_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Revisión de tarea de la leccion',
                'verbose_name_plural': 'Revisiones de tareas de las lecciones',
            },
        ),
        migrations.CreateModel(
            name='HomeworkLessonResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripcion')),
                ('resource', models.FileField(blank=True, null=True, upload_to=training_fyg.courses.models.courses.homework_lesson_resource_directory_path, verbose_name='contenido de la tarea')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklessonresource_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('homework_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworklessonresource', to='courses.homeworklesson', verbose_name='clase')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklessonresource_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Recurso de la tarea',
                'verbose_name_plural': 'Recursos de las tareas',
            },
        ),
        migrations.CreateModel(
            name='HomeworkLessonNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('note', models.CharField(help_text='nota de la entrega de la tarea', max_length=200, verbose_name='nota')),
                ('adjunted_file', models.FileField(blank=True, help_text='Archivo adjunto', null=True, upload_to='', verbose_name='Archivo adjunto')),
                ('note_type', models.CharField(choices=[('Comentario', 'Comentario'), ('Entrega tarea', 'Entrega tarea')], default='Comentario', help_text='Tipo nota', max_length=16, verbose_name='Tipo nota')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklessonnotes_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('homework_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.homeworklesson', verbose_name='tarea entrega a la que pertenece la nota')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklessonnotes_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'nota tarea de la leccion',
                'verbose_name_plural': 'nota tareas de las lecciones',
            },
        ),
        migrations.AddField(
            model_name='homeworklesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworklesson', to='courses.lesson', verbose_name='clase'),
        ),
        migrations.AddField(
            model_name='homeworklesson',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklesson_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor'),
        ),
        migrations.CreateModel(
            name='CourseScheduleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripcion')),
                ('url', models.URLField(default='https://calendar.google.com', verbose_name='Url de la clase')),
                ('start_date', models.DateTimeField(verbose_name='Fecha inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha fin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='curso')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_coursescheduleclass_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='lesson')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_coursescheduleclass_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodule', verbose_name='modulo')),
            ],
            options={
                'verbose_name': 'Clase que el profesor puede agendar en vivo',
                'verbose_name_plural': 'Clases que el profesor puede agendar en vivo',
            },
        ),
        migrations.CreateModel(
            name='CourseInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('email', models.TextField(max_length=10000, verbose_name='Email de estudiante')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='curso')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_courseinvitation_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_courseinvitation_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Invitacion curso',
                'verbose_name_plural': 'Invitaciones Cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('image', models.ImageField(max_length=500, upload_to=training_fyg.courses.models.courses.course_directory_path, verbose_name='Foto')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_courseimage_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_courseimage_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Fotos de curso',
                'verbose_name_plural': 'Fotos del curso',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseimage', verbose_name='Imagen del curso'),
        ),
        migrations.AddField(
            model_name='course',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_course_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor'),
        ),
        migrations.CreateModel(
            name='CourseLessonProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('progress', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Progreso de la lección')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_courselessonprogress_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('lesson', models.ForeignKey(help_text='Lección en proceso', on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Lección')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_courselessonprogress_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de la lección ',
                'verbose_name_plural': 'Progresos de las lecciones',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
