# Generated by Django 3.2.14 on 2022-08-02 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20220802_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkLessonDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro debe ser tratado como activo. Desmarque esta opción en lugar de borrar el registro', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el registro fue creado.', verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Última fecha en que el registro fue modificado', verbose_name='Última modificación')),
                ('note', models.CharField(help_text='Notas de la entrega de la tarea', max_length=200, verbose_name='Nota')),
                ('resource', models.FileField(blank=True, help_text='Archivo adjunto', null=True, upload_to='', verbose_name='Archivo adjunto')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklessondelivery_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador')),
                ('homework_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homeworklesson', verbose_name='Tarea entrega a la que pertenece la entrega')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_homeworklessondelivery_modified', to=settings.AUTH_USER_MODEL, verbose_name='Usuario editor')),
            ],
            options={
                'verbose_name': 'Entrega de tareas',
                'verbose_name_plural': 'Entregas de tareas',
            },
        ),
        migrations.DeleteModel(
            name='HomeworkLessonNotes',
        ),
    ]
