# Generated by Django 3.2.14 on 2022-08-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20220802_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworklesson',
            name='status_type',
        ),
        migrations.AddField(
            model_name='homeworklessondelivery',
            name='status_type',
            field=models.CharField(choices=[('Revisado', 'Revisado'), ('Pendiente', 'Pendiente')], default='Pendiente', help_text='Estatus revision', max_length=10, verbose_name='Estatus revision'),
        ),
    ]
