# Generated by Django 3.2.14 on 2022-08-05 04:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220802_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimage',
            options={'verbose_name': 'Imagen des curso', 'verbose_name_plural': 'Imágenes del curso'},
        ),
        migrations.AlterModelOptions(
            name='courseinvitation',
            options={'verbose_name': 'Invitacion al curso', 'verbose_name_plural': 'Invitaciones a los cursos'},
        ),
        migrations.AlterModelOptions(
            name='homeworklesson',
            options={'verbose_name': 'Tarea de la lección', 'verbose_name_plural': 'Tareas de las lecciones'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], help_text='Tipo de curso, accesible públicamente o por invitación', max_length=12, verbose_name='Tipo de curso'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='courses/courses/course-image/image/%Y/%m/%d/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='courseinvitation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='courseinvitation',
            name='email',
            field=models.TextField(max_length=10000, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursescheduleclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='coursescheduleclass',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='coursescheduleclass',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Lección'),
        ),
        migrations.AlterField(
            model_name='coursescheduleclass',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodule', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='homeworklesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworklesson', to='courses.lesson', verbose_name='Tarea de la lección'),
        ),
        migrations.AlterField(
            model_name='homeworklesson',
            name='title',
            field=models.CharField(default='Título de la tarea', max_length=120, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='homeworklessondelivery',
            name='homework_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homeworklesson', verbose_name='Tarea de la lección'),
        ),
        migrations.AlterField(
            model_name='homeworklessonresource',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='homeworklessonresource',
            name='homework_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworklessonresource', to='courses.homeworklesson', verbose_name='Tarea de la lección'),
        ),
        migrations.AlterField(
            model_name='homeworklessonresource',
            name='resource',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='courses/courses/homework-lesson-resource/resource/%Y/%m/%d/', verbose_name='Recurso de la tarea'),
        ),
        migrations.AlterField(
            model_name='homeworklessonreview',
            name='homework_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeworklessonreview', to='courses.homeworklesson', verbose_name='Revisión de la tarea de lección'),
        ),
        migrations.AlterField(
            model_name='homeworklessonreview',
            name='qualification',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='imageslesson',
            name='resource',
            field=models.FileField(help_text='Son los recursos que se mostraran', max_length=1000, upload_to='courses/courses/images-lesson/resource/%Y/%m/%d/', verbose_name='Recurso de la clase'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='resource',
            field=models.FileField(max_length=500, upload_to='courses/image-lesson/resource/%Y/%m/%d/', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachercourse', to='courses.course', verbose_name='Curso'),
        ),
    ]
