# Generated by Django 3.2.14 on 2022-08-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220804_2311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeworkLessonReview',
        ),
    ]
