# Generated by Django 3.2.14 on 2022-08-05 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_homeworklessonreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeworkLessonReview',
        ),
    ]
