# Generated by Django 3.2.14 on 2022-08-19 15:37

from django.conf import settings
from django.db import migrations


def truncate_student_course_table(apps, schema_editor):
    StudentCourse = apps.get_model("courses", "StudentCourse")
    CourseLessonProgress = apps.get_model("courses", "CourseLessonProgress")
    StudentCourse.objects.all().delete()
    CourseLessonProgress.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_auto_20220819_1029'),
    ]

    operations = [
        migrations.RunPython(truncate_student_course_table),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('user', 'course')},
        ),
    ]
