# Generated by Django 3.2.14 on 2022-08-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_studentcourse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time_taken',
            field=models.PositiveIntegerField(default=5, help_text='Tiempo tomado para completar la lección en minutos', verbose_name='Duración de la lección'),
        ),
    ]
